import os
import re

def remove_extra_newlines_around_display_math(filepath):
    """
    Reads a LaTeX file and removes excessive newlines around \[ and \].
    This prevents extra blank lines before and after display math environments 
    (which are often generated by pandoc from Markdown).

    Args:
        filepath (str): The path to the LaTeX file.
    """
    print(f"Processing file: {filepath}...")

    # Check if the file exists
    if not os.path.exists(filepath):
        print(f"Error: File not found: {filepath}")
        return

    try:
        # 1. Read the file content
        # Use 'r' mode and 'utf-8' encoding for standard LaTeX files
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()

        # 2. Define the replacement patterns
        
        # Target: Replace \n\n\[ with \n\[ (or any number of newlines/blank lines)
        # Regular expression breakdown for the starting delimiter \[ :
        # - (\n\s*)+: Matches one or more occurrences of newline (\n) followed 
        #   by optional whitespace (\s*). This captures multiple blank lines.
        # - \\\[: Matches the literal LaTeX display math start delimiter \[
        pattern_start = re.compile(r'(\n\s*)+\\\[')
        
        # Target: Replace \]\n\n with \]\n (or any number of newlines/blank lines)
        # Regular expression breakdown for the ending delimiter \]:
        # - \\\]: Matches the literal LaTeX display math end delimiter \]
        # - (\n\s*)+: Matches one or more occurrences of newline (\n) followed 
        #   by optional whitespace (\s*).
        pattern_end = re.compile(r'\\](\n\s*)+')

        # 3. Execute the replacements
        
        # Replacement for \[ :
        # We replace the excessive newlines/blank lines with a single newline '\n' 
        # before the literal '\[' to ensure the math starts on the next line 
        # without an extra blank line before it.
        modified_content = pattern_start.sub('\n\\[', content)
        
        # Replacement for \] :
        # We replace the excessive newlines/blank lines with a single newline '\n' 
        # after the literal '\]' to ensure the math ends and the text continues 
        # on the next line without an extra blank line after it.
        modified_content = pattern_end.sub('\\]\n', modified_content)

        # 3b. Remove needless line breaks before list items generated by pandoc
        # Pattern: "\\\\" followed by optional whitespace, then a newline and "\\item"
        # Example to fix:
        #   Foo \\
        #   \item Bar
        # becomes:
        #   Foo
        #   \item Bar
        pattern_item_break = re.compile(r'\\\\\s*\n(\\item)')
        modified_content = pattern_item_break.sub(r'\n\1', modified_content)

        # 4. Write back to a new file (recommended for safety)
        
        # Creates a new filename, e.g., 'document.tex' -> 'document_fixed.tex'
        new_filepath = filepath.replace('.tex', '_fixed.tex')
        
        with open(new_filepath, 'w', encoding='utf-8') as f:
            f.write(modified_content)

        print(f"✅ Processing complete. Modified file saved to: {new_filepath}")
        print("The original file has NOT been modified. Please check the new file.")

        # --- OPTIONAL: Uncomment the following block to overwrite the original file ---
        # Note: Use this with caution!
        # with open(filepath, 'w', encoding='utf-8') as f:
        # #     f.write(modified_content)
        # # print(f"✅ Processing complete. File overwritten: {filepath}")

    except Exception as e:
        print(f"An error occurred during processing: {e}")

file_to_process = 'content.tex' 

# Run the function
remove_extra_newlines_around_display_math(file_to_process)